// Achievement definitions. Each `check` receives the computed stats object
// from computeStats() in app.js and returns true when unlocked.
// Grouped by category so the Achievements screen can section them.

const ACHIEVEMENTS = [
  // ============ FIRST STEPS ============
  { id: "first-blood", cat: "Awakening", name: "First Blood", desc: "Log your first set.", icon: "🩸", check: (s) => s.totalSetsLogged >= 1 },
  { id: "plan-architect", cat: "Awakening", name: "Architect", desc: "Create your first plan.", icon: "📜", check: (s) => s.totalPlans >= 1 },
  { id: "first-split", cat: "Awakening", name: "First Descent", desc: "Complete your first split.", icon: "🗝️", check: (s) => s.totalSplitsCompleted >= 1 },
  { id: "first-weigh", cat: "Awakening", name: "Know Thy Vessel", desc: "Log your weight once.", icon: "⚖️", check: (s) => s.totalWeightLogs >= 1 },
  { id: "first-pr", cat: "Awakening", name: "New Blood", desc: "Set your first personal record.", icon: "💪", check: (s) => s.prCount >= 1 },
  { id: "custom-exercise", cat: "Awakening", name: "Forbidden Rite", desc: "Create a custom exercise.", icon: "🕯️", check: (s) => s.customExercises >= 1 },
  { id: "second-plan", cat: "Awakening", name: "Twin Grimoires", desc: "Have 2 plans at once.", icon: "📚", check: (s) => s.totalPlans >= 2 },
  { id: "full-split", cat: "Awakening", name: "No Retreat", desc: "Finish a split without skipping.", icon: "🛡️", check: (s) => s.perfectSplits >= 1 },
  { id: "three-splits-plan", cat: "Awakening", name: "Trinity", desc: "Build a plan with 3+ splits.", icon: "🔱", check: (s) => s.maxSplitsInPlan >= 3 },
  { id: "loaded-split", cat: "Awakening", name: "Heavy Tome", desc: "Build a split with 8+ exercises.", icon: "📖", check: (s) => s.maxExercisesInSplit >= 8 },

  // ============ STREAKS ============
  { id: "streak-2", cat: "Devotion", name: "Second Night", desc: "2-day streak.", icon: "🌒", check: (s) => s.currentStreak >= 2 },
  { id: "streak-3", cat: "Devotion", name: "Iron Devotion", desc: "3-day streak.", icon: "🔥", check: (s) => s.currentStreak >= 3 },
  { id: "streak-5", cat: "Devotion", name: "Bound", desc: "5-day streak.", icon: "⛓️", check: (s) => s.currentStreak >= 5 },
  { id: "streak-7", cat: "Devotion", name: "Eternal Bond", desc: "7-day streak.", icon: "💜", check: (s) => s.currentStreak >= 7 },
  { id: "streak-10", cat: "Devotion", name: "Ten Nights", desc: "10-day streak.", icon: "🌘", check: (s) => s.currentStreak >= 10 },
  { id: "streak-14", cat: "Devotion", name: "Fortnight Vigil", desc: "14-day streak.", icon: "🕰️", check: (s) => s.currentStreak >= 14 },
  { id: "streak-21", cat: "Devotion", name: "Habit Forged", desc: "21-day streak.", icon: "⚒️", check: (s) => s.currentStreak >= 21 },
  { id: "streak-30", cat: "Devotion", name: "Curse Unbroken", desc: "30-day streak.", icon: "🌙", check: (s) => s.currentStreak >= 30 },
  { id: "streak-50", cat: "Devotion", name: "Half A Hundred", desc: "50-day streak.", icon: "☄️", check: (s) => s.currentStreak >= 50 },
  { id: "streak-75", cat: "Devotion", name: "Unrelenting", desc: "75-day streak.", icon: "🌀", check: (s) => s.currentStreak >= 75 },
  { id: "streak-100", cat: "Devotion", name: "Century Of Nights", desc: "100-day streak.", icon: "👑", check: (s) => s.currentStreak >= 100 },
  { id: "streak-180", cat: "Devotion", name: "Half Year Haunt", desc: "180-day streak.", icon: "🏵️", check: (s) => s.currentStreak >= 180 },
  { id: "streak-365", cat: "Devotion", name: "Immortal", desc: "365-day streak.", icon: "♾️", check: (s) => s.currentStreak >= 365 },
  { id: "best-streak-7", cat: "Devotion", name: "Once Devoted", desc: "Best streak of 7+ days.", icon: "🥉", check: (s) => s.bestStreak >= 7 },
  { id: "best-streak-30", cat: "Devotion", name: "Legend Of The Keep", desc: "Best streak of 30+ days.", icon: "🥈", check: (s) => s.bestStreak >= 30 },
  { id: "comeback", cat: "Devotion", name: "She Forgives You", desc: "Return after a 7+ day absence.", icon: "🩹", check: (s) => s.hasComeback },
  { id: "week-perfect", cat: "Devotion", name: "Flawless Week", desc: "Train all 7 days of a week.", icon: "✨", check: (s) => s.perfectWeeks >= 1 },
  { id: "week-perfect-4", cat: "Devotion", name: "Flawless Month", desc: "4 perfect weeks total.", icon: "🌟", check: (s) => s.perfectWeeks >= 4 },
  { id: "active-days-10", cat: "Devotion", name: "Ten Visits", desc: "10 active days total.", icon: "📆", check: (s) => s.activeDayCount >= 10 },
  { id: "active-days-50", cat: "Devotion", name: "Fifty Visits", desc: "50 active days total.", icon: "🗓️", check: (s) => s.activeDayCount >= 50 },
  { id: "active-days-100", cat: "Devotion", name: "Hundred Visits", desc: "100 active days total.", icon: "📅", check: (s) => s.activeDayCount >= 100 },
  { id: "active-days-250", cat: "Devotion", name: "Resident", desc: "250 active days total.", icon: "🏰", check: (s) => s.activeDayCount >= 250 },

  // ============ SPLITS COMPLETED ============
  { id: "splits-5", cat: "Campaign", name: "Five Trials", desc: "Complete 5 splits.", icon: "⚔️", check: (s) => s.totalSplitsCompleted >= 5 },
  { id: "splits-10", cat: "Campaign", name: "Split Slayer", desc: "Complete 10 splits.", icon: "🗡️", check: (s) => s.totalSplitsCompleted >= 10 },
  { id: "splits-25", cat: "Campaign", name: "Seasoned", desc: "Complete 25 splits.", icon: "🎯", check: (s) => s.totalSplitsCompleted >= 25 },
  { id: "splits-50", cat: "Campaign", name: "Castle Regular", desc: "Complete 50 splits.", icon: "🏰", check: (s) => s.totalSplitsCompleted >= 50 },
  { id: "splits-100", cat: "Campaign", name: "Centurion", desc: "Complete 100 splits.", icon: "🎖️", check: (s) => s.totalSplitsCompleted >= 100 },
  { id: "splits-200", cat: "Campaign", name: "Warlord", desc: "Complete 200 splits.", icon: "🏹", check: (s) => s.totalSplitsCompleted >= 200 },
  { id: "splits-365", cat: "Campaign", name: "One Per Night", desc: "Complete 365 splits.", icon: "🌌", check: (s) => s.totalSplitsCompleted >= 365 },
  { id: "perfect-5", cat: "Campaign", name: "Unskipped", desc: "5 splits with zero skips.", icon: "🛡️", check: (s) => s.perfectSplits >= 5 },
  { id: "perfect-25", cat: "Campaign", name: "Disciplined", desc: "25 splits with zero skips.", icon: "⚜️", check: (s) => s.perfectSplits >= 25 },
  { id: "perfect-50", cat: "Campaign", name: "Machine", desc: "50 splits with zero skips.", icon: "⚙️", check: (s) => s.perfectSplits >= 50 },
  { id: "two-a-day", cat: "Campaign", name: "Twice In One Night", desc: "Complete 2 splits in one day.", icon: "🌗", check: (s) => s.maxSplitsInADay >= 2 },
  { id: "three-a-day", cat: "Campaign", name: "Insatiable", desc: "Complete 3 splits in one day.", icon: "🔺", check: (s) => s.maxSplitsInADay >= 3 },

  // ============ VOLUME: SETS ============
  { id: "sets-10", cat: "Toil", name: "Ten Sets", desc: "Log 10 sets.", icon: "🔟", check: (s) => s.totalSetsLogged >= 10 },
  { id: "sets-50", cat: "Toil", name: "Fifty Sets", desc: "Log 50 sets.", icon: "🧱", check: (s) => s.totalSetsLogged >= 50 },
  { id: "sets-100", cat: "Toil", name: "Hundred Sets", desc: "Log 100 sets.", icon: "💯", check: (s) => s.totalSetsLogged >= 100 },
  { id: "sets-250", cat: "Toil", name: "Grinder", desc: "Log 250 sets.", icon: "🪓", check: (s) => s.totalSetsLogged >= 250 },
  { id: "sets-500", cat: "Toil", name: "Relentless", desc: "Log 500 sets.", icon: "🔨", check: (s) => s.totalSetsLogged >= 500 },
  { id: "sets-1000", cat: "Toil", name: "Thousand Cuts", desc: "Log 1,000 sets.", icon: "🌊", check: (s) => s.totalSetsLogged >= 1000 },
  { id: "sets-2500", cat: "Toil", name: "Beyond Counting", desc: "Log 2,500 sets.", icon: "🌠", check: (s) => s.totalSetsLogged >= 2500 },
  { id: "reps-100", cat: "Toil", name: "Century Reps", desc: "Log 100 total reps.", icon: "🧮", check: (s) => s.totalReps >= 100 },
  { id: "reps-1000", cat: "Toil", name: "Thousand Reps", desc: "Log 1,000 total reps.", icon: "📈", check: (s) => s.totalReps >= 1000 },
  { id: "reps-5000", cat: "Toil", name: "Five Thousand", desc: "Log 5,000 total reps.", icon: "🚀", check: (s) => s.totalReps >= 5000 },
  { id: "reps-10000", cat: "Toil", name: "Ten Thousand Reps", desc: "Log 10,000 total reps.", icon: "🌋", check: (s) => s.totalReps >= 10000 },
  { id: "sets-in-day-20", cat: "Toil", name: "Marathon Night", desc: "Log 20 sets in one day.", icon: "🕸️", check: (s) => s.maxSetsInADay >= 20 },
  { id: "sets-in-day-30", cat: "Toil", name: "Obsession", desc: "Log 30 sets in one day.", icon: "🩸", check: (s) => s.maxSetsInADay >= 30 },

  // ============ VOLUME: TONNAGE ============
  { id: "tonnage-1k", cat: "Tonnage", name: "One Ton", desc: "Move 1,000 kg total.", icon: "🪨", check: (s) => s.totalVolume >= 1000 },
  { id: "tonnage-10k", cat: "Tonnage", name: "Ten Tons", desc: "Move 10,000 kg total.", icon: "⛰️", check: (s) => s.totalVolume >= 10000 },
  { id: "tonnage-50k", cat: "Tonnage", name: "Fifty Tons", desc: "Move 50,000 kg total.", icon: "🗿", check: (s) => s.totalVolume >= 50000 },
  { id: "tonnage-100k", cat: "Tonnage", name: "Hundred Tons", desc: "Move 100,000 kg total.", icon: "🌑", check: (s) => s.totalVolume >= 100000 },
  { id: "tonnage-500k", cat: "Tonnage", name: "Half Million", desc: "Move 500,000 kg total.", icon: "🪐", check: (s) => s.totalVolume >= 500000 },
  { id: "tonnage-1m", cat: "Tonnage", name: "Millionaire", desc: "Move 1,000,000 kg total.", icon: "💎", check: (s) => s.totalVolume >= 1000000 },
  { id: "vol-day-5k", cat: "Tonnage", name: "Heavy Night", desc: "Move 5,000 kg in one day.", icon: "🌘", check: (s) => s.maxVolumeInADay >= 5000 },
  { id: "vol-day-10k", cat: "Tonnage", name: "Crushing", desc: "Move 10,000 kg in one day.", icon: "🕳️", check: (s) => s.maxVolumeInADay >= 10000 },

  // ============ STRENGTH / PRs ============
  { id: "pr-5", cat: "Ascension", name: "Five Records", desc: "Set 5 personal records.", icon: "📊", check: (s) => s.prCount >= 5 },
  { id: "pr-10", cat: "Ascension", name: "Ten Records", desc: "Set 10 personal records.", icon: "📶", check: (s) => s.prCount >= 10 },
  { id: "pr-25", cat: "Ascension", name: "Record Hunter", desc: "Set 25 personal records.", icon: "🏹", check: (s) => s.prCount >= 25 },
  { id: "pr-50", cat: "Ascension", name: "Ever Upward", desc: "Set 50 personal records.", icon: "🗻", check: (s) => s.prCount >= 50 },
  { id: "lift-40", cat: "Ascension", name: "Forty", desc: "Lift 40 kg in a set.", icon: "🥄", check: (s) => s.heaviestLift >= 40 },
  { id: "lift-60", cat: "Ascension", name: "Sixty", desc: "Lift 60 kg in a set.", icon: "🔩", check: (s) => s.heaviestLift >= 60 },
  { id: "lift-80", cat: "Ascension", name: "Eighty", desc: "Lift 80 kg in a set.", icon: "⚓", check: (s) => s.heaviestLift >= 80 },
  { id: "lift-100", cat: "Ascension", name: "Triple Digits", desc: "Lift 100 kg in a set.", icon: "💠", check: (s) => s.heaviestLift >= 100 },
  { id: "lift-120", cat: "Ascension", name: "Beyond Bodyweight", desc: "Lift 120 kg in a set.", icon: "🦾", check: (s) => s.heaviestLift >= 120 },
  { id: "lift-150", cat: "Ascension", name: "Monstrous", desc: "Lift 150 kg in a set.", icon: "👹", check: (s) => s.heaviestLift >= 150 },
  { id: "lift-200", cat: "Ascension", name: "Inhuman", desc: "Lift 200 kg in a set.", icon: "🐉", check: (s) => s.heaviestLift >= 200 },
  { id: "reps-20-set", cat: "Ascension", name: "Endless Set", desc: "Do 20+ reps in one set.", icon: "🌀", check: (s) => s.maxRepsInSet >= 20 },
  { id: "reps-30-set", cat: "Ascension", name: "Lungs Of Iron", desc: "Do 30+ reps in one set.", icon: "🫁", check: (s) => s.maxRepsInSet >= 30 },
  { id: "reps-50-set", cat: "Ascension", name: "Are You Okay", desc: "Do 50+ reps in one set.", icon: "😵", check: (s) => s.maxRepsInSet >= 50 },

  // ============ EXPLORATION ============
  { id: "ex-5", cat: "Exploration", name: "Five Movements", desc: "Log 5 different exercises.", icon: "🧭", check: (s) => s.uniqueExercises >= 5 },
  { id: "ex-10", cat: "Exploration", name: "Ten Movements", desc: "Log 10 different exercises.", icon: "🗺️", check: (s) => s.uniqueExercises >= 10 },
  { id: "ex-25", cat: "Exploration", name: "Wanderer", desc: "Log 25 different exercises.", icon: "🎒", check: (s) => s.uniqueExercises >= 25 },
  { id: "ex-50", cat: "Exploration", name: "Cartographer", desc: "Log 50 different exercises.", icon: "🧿", check: (s) => s.uniqueExercises >= 50 },
  { id: "cat-3", cat: "Exploration", name: "Three Domains", desc: "Train 3 muscle categories.", icon: "🔻", check: (s) => s.uniqueCategories >= 3 },
  { id: "cat-5", cat: "Exploration", name: "Five Domains", desc: "Train 5 muscle categories.", icon: "⭐", check: (s) => s.uniqueCategories >= 5 },
  { id: "cat-all", cat: "Exploration", name: "Nothing Neglected", desc: "Train 8 muscle categories.", icon: "🌐", check: (s) => s.uniqueCategories >= 8 },
  { id: "leg-day", cat: "Exploration", name: "Never Skips", desc: "Log 20 leg sets.", icon: "🦵", check: (s) => (s.setsByCategory["Legs"] || 0) >= 20 },
  { id: "chest-50", cat: "Exploration", name: "Chest Devotee", desc: "Log 50 chest sets.", icon: "🛡️", check: (s) => (s.setsByCategory["Chest"] || 0) >= 50 },
  { id: "back-50", cat: "Exploration", name: "Spine Of Iron", desc: "Log 50 back sets.", icon: "🐍", check: (s) => (s.setsByCategory["Back"] || 0) >= 50 },
  { id: "core-30", cat: "Exploration", name: "Hollow Core", desc: "Log 30 core sets.", icon: "🕷️", check: (s) => (s.setsByCategory["Core"] || 0) >= 30 },
  { id: "cardio-20", cat: "Exploration", name: "Blood Pumping", desc: "Log 20 cardio sets.", icon: "❤️‍🔥", check: (s) => (s.setsByCategory["Cardio"] || 0) >= 20 },
  { id: "custom-5", cat: "Exploration", name: "Own Grimoire", desc: "Create 5 custom exercises.", icon: "✒️", check: (s) => s.customExercises >= 5 },

  // ============ THE SCALE ============
  { id: "weigh-5", cat: "The Scale", name: "Watchful", desc: "Log weight 5 times.", icon: "👁️", check: (s) => s.totalWeightLogs >= 5 },
  { id: "weigh-10", cat: "The Scale", name: "Scale Keeper", desc: "Log weight 10 times.", icon: "⚖️", check: (s) => s.totalWeightLogs >= 10 },
  { id: "weigh-30", cat: "The Scale", name: "Monthly Ritual", desc: "Log weight 30 times.", icon: "🔮", check: (s) => s.totalWeightLogs >= 30 },
  { id: "weigh-100", cat: "The Scale", name: "Obsessive Record", desc: "Log weight 100 times.", icon: "📉", check: (s) => s.totalWeightLogs >= 100 },
  { id: "weigh-streak-7", cat: "The Scale", name: "Seven Mornings", desc: "Log weight 7 days in a row.", icon: "🌅", check: (s) => s.weightStreak >= 7 },
  { id: "weigh-streak-30", cat: "The Scale", name: "Unwavering Eye", desc: "Log weight 30 days in a row.", icon: "🌄", check: (s) => s.weightStreak >= 30 },
  { id: "weight-change-2", cat: "The Scale", name: "The Needle Moves", desc: "Change 2 kg from your first log.", icon: "📐", check: (s) => Math.abs(s.weightDelta) >= 2 },
  { id: "weight-change-5", cat: "The Scale", name: "Transformation", desc: "Change 5 kg from your first log.", icon: "🦋", check: (s) => Math.abs(s.weightDelta) >= 5 },
  { id: "weight-change-10", cat: "The Scale", name: "Reborn", desc: "Change 10 kg from your first log.", icon: "🔥", check: (s) => Math.abs(s.weightDelta) >= 10 },

  // ============ LEVELS ============
  { id: "level-3", cat: "Legend", name: "Initiate", desc: "Reach level 3.", icon: "🕯️", check: (s) => s.level >= 3 },
  { id: "level-5", cat: "Legend", name: "Night's Disciple", desc: "Reach level 5.", icon: "🦇", check: (s) => s.level >= 5 },
  { id: "level-10", cat: "Legend", name: "Adept", desc: "Reach level 10.", icon: "🌒", check: (s) => s.level >= 10 },
  { id: "level-20", cat: "Legend", name: "Revenant", desc: "Reach level 20.", icon: "💀", check: (s) => s.level >= 20 },
  { id: "level-35", cat: "Legend", name: "Nightlord", desc: "Reach level 35.", icon: "🌑", check: (s) => s.level >= 35 },
  { id: "level-50", cat: "Legend", name: "Eternal", desc: "Reach level 50.", icon: "👑", check: (s) => s.level >= 50 },
  { id: "level-75", cat: "Legend", name: "Mythic", desc: "Reach level 75.", icon: "🌟", check: (s) => s.level >= 75 },
  { id: "level-100", cat: "Legend", name: "Beyond Death", desc: "Reach level 100.", icon: "♾️", check: (s) => s.level >= 100 },

  // ============ ODDITIES ============
  { id: "night-owl", cat: "Oddities", name: "Creature Of Night", desc: "Log a set after 10pm.", icon: "🌃", check: (s) => s.loggedLate },
  { id: "early-bird", cat: "Oddities", name: "Before The Sun", desc: "Log a set before 6am.", icon: "🌤️", check: (s) => s.loggedEarly },
  { id: "weekend-warrior", cat: "Oddities", name: "Weekend Warrior", desc: "Train on 10 weekend days.", icon: "🎪", check: (s) => s.weekendDays >= 10 },
  { id: "rest-skipper", cat: "Oddities", name: "No Rest For You", desc: "Skip the rest timer 25 times.", icon: "⏭️", check: (s) => s.restsSkipped >= 25 },
  { id: "patient", cat: "Oddities", name: "Patient Soul", desc: "Let the rest timer finish 25 times.", icon: "⏳", check: (s) => s.restsCompleted >= 25 },
  { id: "collector", cat: "Oddities", name: "Collector", desc: "Unlock 25 achievements.", icon: "🏆", check: (s) => s.unlockedCount >= 25 },
  { id: "completionist", cat: "Oddities", name: "Completionist", desc: "Unlock 50 achievements.", icon: "🥇", check: (s) => s.unlockedCount >= 50 },
  { id: "her-favorite", cat: "Oddities", name: "Her Favorite", desc: "Unlock 75 achievements.", icon: "💗", check: (s) => s.unlockedCount >= 75 },
];
